### ISSUE TITLE
Unable to "learn test"

### ISSUE THREAD

**Issue by twallingford** [learn-co-curriculum/phase-0-css-intro-lab#22]
### Canvas Link

https://learning.flatironschool.com/courses/6324/assignments/214200?module_item_id=496804

### Concern

Based on the error I am getting, I don't think it's my code that's causing the problem. It looks like it's on lines 26 and 27 of indexTest.js.

### Additional Context

When trying to use "learn test" I get this error

> phase-0-css-intro-lab@1.0.0 test
> mocha -R mocha-multi --timeout 5000 --reporter-options spec=-,json=.results.json

/home/twallingford/Development/code/prework/phase-0-css-intro-lab/test/indexTest.js:26
      .join("
            ^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async formattedImport (/home/twallingford/Development/code/prework/phase-0-css-intro-lab/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async exports.requireOrImport (/home/twallingford/Development/code/prework/phase-0-css-intro-lab/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async exports.loadFilesAsync (/home/twallingford/Development/code/prework/phase-0-css-intro-lab/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/home/twallingford/Development/code/prework/phase-0-css-intro-lab/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/home/twallingford/Development/code/prework/phase-0-css-intro-lab/node_modules/mocha/lib/cli/run.js:374:5)
twallingford@Zero:~/Development/code/prework/phase-0-css-intro-lab$ Traceback (most recent call last):
        11: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
        10: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
         9: from /usr/share/rvm/gems/ruby-2.7.4/bin/learn-test:25:in `<main>'
         8: from /usr/share/rvm/gems/ruby-2.7.4/bin/learn-test:25:in `load'
         7: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/bin/learn-test:73:in `<top (required)>'
         6: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/runner.rb:21:in `run'
         5: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/runner.rb:21:in `fork'
         4: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/runner.rb:22:in `block in run'
         3: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/runner.rb:49:in `report_and_clean'
         2: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/reporter.rb:47:in `report'
/usr/share/rvm/gems/ruby-2.7.4/gems/learn-test-3.3.1/lib/learn_test/strategies/mocha.rb:44:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

I've looked it over and can't find anything there relating to my code and, based on how the test page looks, it appears that the assignment is done correctly.

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
